QUOTES = ["Your reputation is more important than your paycheck, and your integrity is worth more than your career.  By Ryan Freitas, About.me co-founder",
"Every time we launch a feature, people yell at us. By Angelo Sotira, deviantART co-founder",
"Be undeniably good. No marketing effort or social media buzzword can be a substitute for that. By Anthony Volodkin, Hype Machine founder",
"Money is like gasoline during a road trip. You don't want to run out of gas on your trip, but you're not doing a tour of gas stations. By Tim O'Reilly, O'Reilly Media founder and CEO",
"If you can't feed a team with two pizzas, it's too large. By Jeff Bezos, Amazon founder and CEO",
"Don't worry about people stealing your design work. Worry about the day they stop. By Jeffrey Zeldman, A List Apart Publisher",
"Chase the vision, not the money, the money will end up following you. By Tony Hsieh, Zappos CEO",
"The value of an idea lies in the using of it. By Thomas Edison, General Electric Co-founder",
"Make every detail perfect and limit the number of details to perfect. By Jack Dorsey, Twitter co-founder",
"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. By Steve Jobs, Apple Inc. co-founder, chairman and CEO",
"The most dangerous poison is the feeling of achievement. The antidote is to every evening think what can be done better tomorrow. By Ingvar Kamprad, IKEA founder",
"Always look for the fool in the deal. If you don't find one, it's you. By Mark Cuban, AXS TV chairman and entrepreneur",
"It's not about ideas. It's about making ideas happen. By Scott Belsky, Behance co-founder",
"There's nothing wrong with staying small. You can do big things with a small team. By Jason Fried, 37signals founder",
"Don't worry about failure; you only have to be right once. By Drew Houston, Dropbox founder and CEO",
"Get five or six of your smartest friends in a room and ask them to rate your idea. By Mark Pincus, Zynga CEO",
"If there's something you want to build, but the tech isn't there yet, just find the closest possible way to make it happen. By Dennis Crowley, Foursquare co-founder",
"Fail often so you can succeed sooner. By Tom Kelley, Ideo partner",
"Nothing works better than just improving your product. By Joel Spolsky, Stack Overflow co-founder and creator of Trello",
"It's not that we need new ideas, but we need to stop having old ideas. By Edwin Land, Polaroid co-founder",
"We are currently not planning on conquering the world. By Sergey Brin, Google co-founder",
"Get big quietly, so you don't tip off potential competitors. By Chris Dixon, personal investor",
"Don't try to be original, just try to be good. By Paul Rand, graphic designer",
"It's hard to do a really good job on anything you don't think about in the shower. By Paul Graham, YCombinator co-founder",
"If you're interested in the living heart of what you do, focus on building things rather than talking about them. By Ryan Freitas, About.me co-founder",
"An entrepreneur is someone who has a vision for something and a want to create. By David Karp, Tumblr founder and CEO",
"The best startups generally come from somebody needing to scratch an itch. By Michael Arrington, TechCrunch founder and co-editor",
"I don't think an economic slump will hurt good ideas. By Rob Kalin, Etsy founder",
"The last 10% it takes to launch something takes as much energy as the first 90%. By Rob Kalin, Etsy founder",
"Don't play games that you don't understand, even if you see lots of other people making money from them. By Tony Hsieh,  Zappos CEO",
"Ideas are easy. Implementation is hard. By Guy Kawasaki, Alltop co-founder and entrepreneur",
"Every day that we spent not improving our products was a wasted day. By Joel Spolsky, Stack Exchange CEO",
"I doubt I'll ever go back to corporate work. Once you see the light, there is no turning back. By Magnus Jepson, WooThemes co-founder",
"Stay self-funded as long as possible. By Garrett Camp, founder of Expa, Uber and StumbleUpon",
"Timing, perseverance, and ten years of trying will eventually make you look like an overnight success. By Biz Stone, Twitter co-founder",
"The only thing worse than starting something and failing... is not starting something. By Seth Godin, Squidoo founder, author and blogger",
"When I'm old and dying, I plan to look back on my life and say 'wow, that was an adventure,' not 'wow, I sure felt safe.' By Tom Preston-Werner, Github co-founder",
"Turn a perceived risk into an asset. By Aaron Patzer, Mint founder",
"Anything that is measured and watched, improves. By Bob Parsons, GoDaddy founder",
"Fortunes are built during the down market and collected in the up market. By Jason Calacanis, LAUNCH Ticker founder",
"No more romanticizing about how cool it is to be an entrepreneur. It's a struggle to save your company's life By and your own skin By every day of the week. By Spencer Fry, CarbonMade co-founder",
"The secret to successful hiring is this: look for the people who want to change the world. By Marc Benioff, Salesforce CEO",
"I try not to make any decisions that I'm not excited about. By Jake Nickell, Threadless founder and CEO",
"See things in the present, even if they are in the future. By Larry Ellison, Oracle co-founder",
"If you're going to put your product in beta By put your business model in beta with it. By Joe Kraus, Google Ventures partner",
"You can't make anything viral, but you can make something good. By Peter Shankman, HARO founder",
"It's more effective to do something valuable than to hope a logo or name will say it for you. By Jason Cohen, Smart Bear Software founder",
"Don't worry about funding if you don't need it. Today it's cheaper to start a business than ever. By Noah Everett, Twitpic founder",
"Ideas are commodity. Execution of them is not. By Michael Dell, Dell chairman and CEO",
"Data beats emotions. By Sean Rad, Adly and Tinder founder",
"I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not trying. By Jeff Bezos, Amazon founder and CEO",
"You don't need to have a 100-person company to develop that idea. By Larry Page, Google co-founder",
"A 'startup' is a company that is confused about By 1. What its product is. 2. Who its customers are. 3. How to make money. By Dave McClure, 500Startups co-founder",
"If you are not embarrassed by the first version of your product, you've launched too late. By Reid Hoffman, LinkedIn co-founder",
"All humans are entrepreneurs not because they should start companies but because the will to create is encoded in human DNA. By Reid Hoffman, LinkedIn co-founder",
"Before dreaming about the future or making plans, you need to articulate what you already have going for you - as entrepreneurs do. By Reid Hoffman, LinkedIn co-founder",
"No matter how brilliant your mind or strategy, if you're playing a solo game, you'll always lose out to a team. By Reid Hoffman, LinkedIn co-founder",
"The fastest way to change yourself is to hang out with people who are already the way you want to be. By Reid Hoffman, LinkedIn co-founder",
"I don't look to jump over 7-foot bars -By I look for 1-foot bars that I can step over. By Warren Buffet, Berkshire Hathaway chairman and CEO",
"In the end, a vision without the ability to execute it is probably a hallucination. By Steve Case, AOL co-founder",
"Don't be cocky. Don't be flashy. There's always someone better than you. By Tony Hsieh, Zappos CEO",
"Embrace what you don't know, especially in the beginning, because what you don't know can become your greatest asset. It ensures that you will absolutely be doing things different from everybody else. By Sara Blakely,  SPANX founder",
"What do you need to start a business? Three simple things: know your product better than anyone. Know your customer, and have a burning desire to succeed. By Dave Thomas, Founder, Wendy's",
"As long as you're going to be thinking anyway, think big. By Donald Trump, The Trump Organization president",
"Whether you think you can, or think you can't - you're right. By Henry Ford, Ford Motor Company founder",
"Behold the turtle, he makes progress only when he sticks his neck out. By Bruce Levin",
"Fearlessness is like a muscle. I know from my own life that the more I exercise it the more natural it becomes to not let my fears run me. By Arianna Huffington The Huffington Post Media Group president and EIC",
"Risk more than others think is safe. Dream more than others think is practical. By Howard Schultz, Starbucks CEO",
"Diligence is the mother of good luck. By Benjamin Franklin",
"You shouldn't focus on why you can't do something, which is what most people do. You should focus on why perhaps you can, and be one of the exceptions. By Steve Case, AOL co-founder",
"The way to get started is to quit talking and begin doing. By Walt Disney, Disney founder",
"A person who is quietly confident makes the best leader. By Fred Wilson, Union Square Ventures co-founder",
"We are really competing against ourselves, we have no control over how other people perform. By Pete Cashmore, Mashable founder and CEO",
"I like to pride myself on thinking pretty long term, but not that long term. By Mark Zuckerberg, Facebook founder",
"Always deliver more than expected. By Larry Page, Google co-founder",
"Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. By Mary Kay Ash, Mary Kay Cosmetics founder",
"You don't learn to walk by following rules. You learn by doing and falling over. By Richard Branson, Virgin Group founder",
"I never took a day off in my twenties. Not one. By Bill Gates,  Microsoft co-founder",
"Even if you don't have the perfect idea to begin with, you can likely adapt. By Victoria Ransom, Wildfire Interactive co-founder",
"High expectations are the key to everything. By Sam Walton, Walmart founder",
"Don't take too much advice. Most people who have a lot of advice to give - with a few exceptions - generalize whatever they did. Don't over-analyze everything.  I myself have been guilty of over-thinking problems. Just build things and find out if they work. By Ben Silbermann, Pinterest founder",
"You just have to pay attention to what people need and what has not been done. By Russell Simmons, Def Jam founder",
"You jump off a cliff and you assemble an airplane on the way down. By Reid Hoffman, LinkedIn co-founder",
"Don't be afraid to assert yourself, have confidence in your abilities and don't let the bastards get you down. By Michael Bloomberg, Bloomberg L.P. founder",
"Every time you state what you want or believe, you're the first to hear it. It's a message to both you and others about what you think is possible. Don't put a ceiling on yourself By Oprah Winfrey, Harpo Productions, OWN founder",
"I made a resolve then that I was going to amount to something if I could. And no hours, nor amount of labor, nor amount of money would deter me from giving the best that there was in me. And I have done that ever since, and I win by it. I know. By Harland Sanders, KFC founder",
"So often people are working hard at the wrong thing. Working on the right thing is probably more important than working hard. By Caterina Fake, Flickr co-founder",
"Trust your instincts. By Estee Lauder, Estee Lauder founder",
"There's lots of bad reasons to start a company. But there's only one good, legitimate reason, and I think you know what it is: it's to change the world. By Phil Libin, Evernote CEO",
"If you're not a risk taker, you should get the hell out of business. By Ray Kroc, McDonald's founder",
"Theory is splendid but until put into practice, it is valueless. By James Cash Penney, J.C. Penney founder",
"Sustaining a successful business is a hell of a lot of work, and staying hungry is half the battle. By Wendy Tan White, MoonFruit co-founder and CEO",
"Your most unhappy customers are your greatest source of learning. Bill Gates, Microsoft co-founder",
"If you define yourself by how you differ from the competition, you're probably in trouble. By Omar Hamoui, AdMob co-founder",
"Design is not just what it looks like and feels like. Design is how it works. By Steve Jobs,  Apple Inc. co-founder, chairman and CEO",
"If you just work on stuff that you like and you're passionate about, you don't have to have a master plan with how things will play out. By Mark Zuckerberg, Facebook founder",
"Wonder what your customer really wants? Ask. Don't tell. By Lisa Stone, BlogHer co-founder and CEO",
"If you're passionate about something and you work hard, then I think you will be successful. By Pierre Omidyar, Ebay founder and chairman",
"Get a mentor in the applicable field if you're at all unsure of what you're looking for. By Kyle Bragger, Forrst founder",
"When you find an idea that you just can't stop thinking about, that's probably a good one to pursue. By Josh James, Omniture CEO and co-founder",
"An invention that is quickly accepted will turn out to be a rather trivial alteration of something that has already existed. By Edwin Land, Polaroid co-founder"]

from random import choice

def lambda_handler(event, context):    
    return {
		'version': 1.0,
		'response': {
			'outputSpeech': {
				'type': 'PlainText',
				'text': choice(QUOTES)
			},
			'shouldEndSession': True
		},
		'sessionAttributes': {}
	}